### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by MatthewMueller** [rc0x03/node-osmosis#1] opened 2015-04-02 18:32 UTC
After installing and trying the example, I get the following error:

```
Error: Cannot find module '/usr/lib/node_modules/needle'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/matt/Playground/osmosis/node_modules/osmosis/index.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

After updating that require, I'm getting:

```
/Users/matt/Playground/osmosis/node_modules/osmosis/node_modules/needle/lib/needle.js:562
        throw new TypeError('Invalid type for ' + key);
              ^
TypeError: Invalid type for follow
    at Object.exports.defaults (/Users/matt/Playground/osmosis/node_modules/osmosis/node_modules/needle/lib/needle.js:562:15)
    at Object.<anonymous> (/Users/matt/Playground/osmosis/node_modules/osmosis/index.js:49:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/matt/Playground/osmosis/index.js:1:77)
    at Module._compile (module.js:456:26)
```

**Comment by rc0x03** [comment] 2015-04-02 20:37
The first error was a problem caused by hard-linking the needle module due to ''/usr/lib/node_modules/needle" in index.js. The second error was caused by Needle no longer accepting a boolean value for its `follow` option. The default for Osmosis has been changed from `follow:true` to `follow:3` to allow following up to 3 redirects. This issue is fixed in the latest commit.

Please be patient with errors that may arise. Osmosis is still in a very early stage. I'm still making some major decisions about its functionality and syntax.

**Closed** 2015-04-04 05:36 UTC
