### ISSUE TITLE
Memory usage & node count grows without bounds

### ISSUE THREAD

**Issue by crystalline** [rc0x03/node-osmosis#65] opened 2016-01-05 00:31 UTC
Hi, I'm using node-osmosis to parse a large set of pages (its a very good library, it works where xray doesn't).
I place osmosis.get(...).set(...).follow(...).set(...).data(...).done(...) invocation into a function, then call this function repeatedly via setTimeout placed in .done(...) callback
The parser works as intended (invocations do not interfere with each other), but I observe unlimited growth of memory & nodes usage by libxml until it crashes node when RAM usage grows > 8GB.

I tried to renew context with calls to osmosis.doc() and osmosis.fail('*') after .done() callback to no effect.
It seems like in this scenario nodes are not freed. I find it problematic because there is no way to create new osmosis instance via API (require returns the same object).

Thus I have a question: how to free memory after I'm done parsing a set of pages (e.g. after .done() callback is called).

**Comment by rc0x03** [comment] 2016-01-05 21:50
This leak is caused by the way libxmljs-dom implements `Document.location`. It will be fixed in the next version.

**Comment by rc0x03** [comment] 2016-01-12 00:20
Fixed in 0.1.2

**Closed by rc0x03** 2016-01-12 00:20 UTC

**Comment by patrickml** [comment] 2016-02-08 19:23
@rc0x03 can you push 0.1.2 into the npm registry? error: osmosis version 0.1.2 is not available in the npm registry
