### ISSUE TITLE
Something wrong with CSS Selector in Version 0.0.5

### ISSUE THREAD

**Issue by ninozhang** [rc0x03/node-osmosis#13] opened 2015-04-12 10:33 UTC
Code: 
{
        'city': '.cityName h3',
        'district': '.cityName h1',
        'current': '.sk .tem span',
        'wet': '.sk .num .sp1',
        'wind': '.sk .num .sp2',
-->   'otherCity[]': '.city li a span',
        'otherCityLink[]': '.city li a@href'
}

'.city li a span' works fine in v0.0.4.
But in v0.0.5 show this message:
omsosis DEBUG (get) starting instance 2
XPath error : Invalid expression
.//*[contains(concat(' ',normalize-space(@class),' '),' city ')]//li a//span

Plz help..

**Comment by davious** [comment] 2015-04-12 14:34
I've run into a similar issue ```#id tbody tr``` fails, while ```#id > tbody > tr``` works.

```
XPath error : Invalid expression
.//*[@id='id']//tbody tr
                      ^
```

interestingly ```#id div div``` only generates 
```
XPath error : Invalid expression
xmlXPathEval: evaluation failed
```

**Comment by rc0x03** [comment] 2015-04-12 19:19
This issue was due to an update improving quote escaping in selectors. The issue is fixed in 0.0.6. Please try the latest version and let me know if you have any more issues as Osmosis is undergoing many changes and enhancements.

**Comment by davious** [comment] 2015-04-12 19:32
https://github.com/rc0x03/node-osmosis/issues/13#issuecomment-92071064 is good now

**Closed** 2015-04-12 20:00 UTC

**Comment by robert26bussard51** [comment] 2015-04-12 20:12
RÖB

**Comment by robert26bussard51** [comment] 2015-04-12 20:12
RÖB
